### ISSUE TITLE
Account Label does not get updated

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#166]
When the account label is given a name, the label still says no label description. It needs a screen refresh before it gets updated.

**Comment by fyahfox** [comment]
With 0.5.4-BETA I noticed this with Firefox 35.0.1 as well.
And not only that, but the popup windows for changing the account label does not disappear when you press "Change". The change is done anyway, but you can only see it after reloading the browser page.

**Comment by Jaguar0625** [comment]
This should be fixed.

**Comment by fyahfox** [comment]
0.5.18-BETA with NCC GUI in Firefox 36.0.1 on Windows 7

Displayed label of account in account list is now immediately changed, but popup is still not showing the new label:
http://s15.postimg.org/txm5wj1sb/change_label_bug.png
