### ISSUE TITLE
NCC web interface -> wallet log in -> no password entered / wrong password entered

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#256]
When you don't enter a password and try to log into your wallet, it displays:
"ERROR 400

Some parameter is missing or invalid."
instead of something like "You have to enter a password." or simply "The password is not correct.".

When you enter the wrong password, it displays:
"ERROR 124

The provided password for the address book is not correct."

**Comment by BloodyRookie** [comment]
If the password is missing, then it will throw an exception very early within ncc (in the spring framework to be precise) because the data from the GUI cannot be deserialized. To respond with a meaning message we need to catch a missing password in the GUI itself.

**Comment by fyahfox** [comment]
Yes, I think that should be done (catch a missing password in the GUI).

**Comment by BloodyRookie** [comment]
Actually I was wrong, we could catch that in NCC. But it is easier in the GUI. Fixed in next release :)

**Comment by gimer** [comment]
will be avail in upcoming build

**Comment by fyahfox** [comment]
Still an issue:

NCC GUI, wallet login page: When you enter a wrong password, it displays:
"ERROR 124

The provided password for the address book is not correct."

Address book is wrong, it should be wallet password or just password.
